begin
  a.i_dont_exist(42)
rescue
  puts 'Something is wrong.'
end
